### ISSUE TITLE
Add basic automated testing using GitHub Actions

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#13]
This should ensure us that out plugin works on plain WIndows servers.

 * Write some simple tests to check if WinFFI/HKPD returns (at least) some values.
 * Activate CI on GitHub actions, and run tests on Windows Servers.

**Comment by daipom** [comment]
Add a simple test to check if this can take all kinds of records at 8c11c22180fd3d513329891df3a2c6b9d893ab84.

**Comment by fujimotos** [comment]
> Add a simple test to check if this can take all kinds of records at 8c11c22.

@daipom  I set up GitHub Actions in a5b1bb5c to execute that test automatically.

You can check that CI is working in the "Actions" tab:

https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/runs/4579188195

**Comment by daipom** [comment]
@fujimotos Thank you! I can check CI is working.

**Comment by fujimotos** [comment]
Let's mark this ticket as done.

**Comment by fujimotos** [comment]
Talking about WIndows Server 2022, it seems that Fluentd fails to install
on that platform.

https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/actions/runs/1600910542

We need to fix this issue in the upstream project first, in order to enable our
testing on WinServer 2022.
