### ISSUE TITLE
Add 32bit Windows support

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#15]
Branched from: https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/issues/1#issuecomment-997494220

**Comment by daipom** [comment]
I have fixed this at 3560029a3ecf26d7a3b0dd934d13ba76224f1eca, though I don't have a 32bit environment and can't test this fix.

**Comment by fujimotos** [comment]
I'll fire up a 32-bit instance on Azure today, and see if our plugin works. WFM.

**Comment by daipom** [comment]
Please. Thank you.

**Comment by fujimotos** [comment]
FTR, I could confirm that our plugin works on x86 WIn10.

 * The tested version is 3560029a3ecf26d7a3b0dd934d13ba76224f1eca.
 * I can confirm out plugin can collect system metrics without any errors.
 * The following table shows the difference between Prometheus exporter (x86) on that system.
   * Every metric is basically A-okay.

| Metrics | fluentd x86| promethes x86 | Difference |
| ------- | ------- | --------- | ---------- |
| windows_memory_cache_bytes | 75804672.0 | 76718080.0 | +1% |
| windows_memory_committed_bytes | 2267979776.0 | 2128949248.0 | -6% |
| windows_memory_free_and_zero_page_list_bytes | 129871872.0 | 133783552.0 | +3% |
| windows_memory_free_system_page_table_entries | 107428.0 | 108961.0 | +1% |
| windows_memory_modified_page_list_bytes | 31784960.0 | 31191040.0 | -1% |
| windows_memory_standby_cache_normal_priority_bytes | 503365632.0 | 511049728.0 | +1% |
| windows_memory_standby_cache_reserve_bytes | 279314432.0 | 271454208.0 | -2% |
| windows_memory_system_cache_resident_bytes | 75804672.0 | 76718080.0 | +1% |
| windows_os_physical_memory_free_bytes | 996524032.0 | 1012473856.0 | +1% |
| windows_os_timezone{timezone="PST"} | N/A | 1.0 | N/A |

**Comment by fujimotos** [comment]
The following is the WIndows version I used for the testing:

```cmd
% systeminfo
...
OS Name:                   Microsoft Windows 10
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Model:              Virtual Machine
System Type:               X86-based PC
...
```

**Comment by daipom** [comment]
@fujimotos Thank you for the confirmation!
I'm glad that fix works.
