### ISSUE TITLE
Add support for Ruby 3.1

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#16]
**Introduction**

We are plannning to bundle `fluent-plugin-windows-exporter` in TD Agent,
starting from the next version (the release date will be March 2022).

Since TD Agent is now moving to Ruby 3.x, we also need to confirm that
this plugin works on Ruby 3.1 as well.

**Task**

- [x] Add Ruby 3.1 to GitHub Actions CI.
  - Use matrix notation to test **both** on 2.7 and 3.1.
  - Here is [an example](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/master/.github/workflows/windows.yml#L11)
- [x] Fix anything that are not compatible with Ruby 3.x.

**Strategic priority**

See https://github.com/fluent/fluentd/pull/3585 for migration status.

**Comment by daipom** [comment]
@fujimotos
Thank you for the clear assignment.

https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/actions/runs/1845181374

I have added Ruby 3.1 in the `add-ci-support-ruby31` branch
and all tests have passed in Ruby 3.1.

Would merging this into master complete this task?

**Comment by fujimotos** [comment]
@daipom Thank you! Marged via 6e3833d80a6d7df7c07e3303a22481f00212a509.

**Comment by daipom** [comment]
Thank you for merging!

**Comment by fujimotos** [comment]
Addendum: I documented the supported Ruby version in 8c9ad68d5def9d3715086ea4e1a53e9cefc0a433.

**Comment by daipom** [comment]
Nice! Thank you!
