### ISSUE TITLE
Implement ffi interface for GlobalMemoryStatusEx() (and others)

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#2]
It turned out that Prometheus `os` collector does not use WMI (despite that [the documentatoin states otherwise](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.os.md)).

 * It uses the following API to retrieve the system infroamtion
   * `GlobalMemoryStatusEx()`
   * `NetWkstaGetInfo()`
   * `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management`
   * `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion`
 * See the following implementation for details 
   * https://github.com/prometheus-community/windows_exporter/blob/master/collector/os.go#L160

We need to implement the same logic in Ruby to replicate the output.

**Comment by fujimotos** [comment]
`NetWkstaGetInfo()`
https://docs.microsoft.com/en-us/windows/win32/api/lmwksta/nf-lmwksta-netwkstagetinfo

`GlobalMemmoryStatusEx()`
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex

We use Ruby's fiddle (libffi) interface
https://docs.ruby-lang.org/ja/2.7.0/library/fiddle.html
https://ruby-doc.org/stdlib-2.7.5/libdoc/fiddle/rdoc/Fiddle.html

**Comment by daipom** [comment]
I was surprised to find that the `os` collector collects information about memory,
such as `PhysicalMemoryFreeBytes`, using 'GlobalMemoryStatusEx'.

https://github.com/prometheus-community/windows_exporter/blob/master/collector/os.go#L244-L248

The `Memory` collector, on the other hand, seems to be collecting information only from `HKEY_PERFORMANCE_DATA`.

I don't understand why the `os` collector has to collect such memory information using `GlobalMemoryStatusEx`.

**Comment by fujimotos** [comment]
My theory is that they initially used `WMI::Win32_OperatingSystem` (which contains
bits about memory status) to implement `os` collector.
 
And it turned out that the performance was not  so great, so they switched to `GlobalMemroyStatusEx`
while keeping the output data format.

**Comment by fujimotos** [comment]
I think I found a bug in FIddle. Posted a bug ticket to the upstream fiddle project: https://github.com/ruby/fiddle/issues/99

**Comment by fujimotos** [comment]
> * GlobalMemoryStatusEx()
> * NetWkstaGetInfo()
> * HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
> * HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion

Done implementing them. Stil it DEFINITELY needs testing, though,

**Comment by fujimotos** [comment]
Let's mark this ticket done. I'll proceed to implement `os` collecctor #3
